### ISSUE TITLE
Does not loads on Microsoft Edge or Internet Explorer

### ISSUE THREAD

**Issue by biraescudero** [epam/med3web#18]
I have the newest Windows 10 ( april/23/2019) and the example page 
https://med3web.opensource.epam.com/ found at https://lifescience.opensource.epam.com/mri/ does not load the images and keeps frozen.

It works fine on Chrome.

Is there any compatibility with these browsers, specially Edge?

**Comment by VladislavShubnikov** [comment]
Our render engine is based on WebGL 2.0, and only limited number of browsers are supported WebGL 2.0. Accroding to 
https://caniuse.com/#feat=webgl2
only Chrome, Firefox, Opera - based browsers are working fine with WebGL 2.0. Others cant work or work with some important limitations, like impossibility to support float point texture and so on.
Answer to your question: Edge browser is NOT supported by our app (due to Edge is not supported WebGL 2.0).

At this time we are working under new version of our app (in branch feature/reactjs), based on ReactJS, and this version will correctly check browser/webgl compatibility. This functionality will be ready in 2-3 monthes later.

**Comment by biraescudero** [comment]
Hi,

Thank you for your fast a clear answer.
I believe we can surpass this probllem only using compatible browsers.
We'll also check the new version when available.

Dest regards,

Ubirajara
